name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        run: |
          sudo apt install neofetch -y
          neofetch
          
      - name: setup environment
        run: sudo apt install bc debhelper-compat binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils libdw-dev:native -y
        
      - name: Get Kernel
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.15.6.tar.xz
          tar -xvf linux-6.15.6.tar.xz
          cp config linux-6.15.6/.config
          cd linux-6.15.6
          
      - name: Build Kernel!!!!
        run: make -j$(nproc)

      - name: Build deb package
        run: |
          git init
          git add .
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"
          git commit -m "Initial commit"
          make deb-pkg -j$(nproc)
          cd ../
          mkdir upload
          mv *.deb upload
      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
          touch release.txt
          [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "🔗 [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware to release
        uses: softprops/action-gh-release@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ upload }}/*
